app/__init__.py
from flask import Flask
from flask_assets import Environment, Bundle

def create_app(config='instance.config.DevelopmentConfig'):
    app = Flask(__name__)
    
    app.config.from_object(config)
    print(f"Environment: {app.config['ENV']}")
    print(f"Debug: {app.config['DEBUG']}")
    print(f"Secret key: {app.config['SECRET_KEY']}")
    
    from app.main.routes import main
    app.register_blueprint(main)
    
    assets = Environment(app)
    
    style_bundle = Bundle(
        'src/sass/style.scss',
        filters='scss,cssmin',
        depends='src/sass/*.scss',
        output='dist/css/style.min.css',
        extra={'rel': 'stylesheet/css'}   
    )
    js_bundle = Bundle(
        'src/js/main.js',
        filters='jsmin',
        output='dist/js/main.min.js'
    )

    assets.register('main_styles', style_bundle)
    assets.register('main_js', js_bundle)
    style_bundle.build()
    js_bundle.build()
    
    return app

app/main/routes.py
from flask import render_template, request, Blueprint
import json

main = Blueprint('main', __name__)

@main.route('/')
def home():
    return render_template('main/index.html')

@main.route('/produkter')
def products():
    with open('app/static/products.json', encoding='utf-8') as db:
        products = json.load(db)
    return render_template('produkter/index.html', products = products)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover"> 
    <link rel="shortcut icon" href="{{url_for('static', filename='img/favicon.png')}}" type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {% assets "main_styles" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css" />
    {% endassets %}
    {% assets 'main_js' %}
    <script src="{{ ASSET_URL }}"></script>
    {% endassets %}
    <title>{%block title%}{%endblock%} - Kant Design</title>
</head>

<body>
    <header>
        <div class="img">
            <img src="{{url_for('static', filename='img/logo.png')}}" alt="logo" id="logo" width="130px" height="auto">
        </div>
        <a href="#nav" class="nav-toggle"></a>
        <nav id="nav">
            <ul id="ul-nav">
                <li><a href="{{url_for('main.home')}}#hem" data-id="hem">Hem</a></li>
                <li><a href="{{url_for('main.home')}}#om-kant">Om Kant</a></li>
                <li><a href="{{url_for('main.products')}}">Produkter</a></li>
                <li><a href="{{url_for('main.home')}}#kontakt">Kontakt</a></li>
            </ul>
        </nav>
    </header>
    {%block content%}{%endblock%}
</body>

</html>

app/templates/main/index.html
{%extends "base.html"%}
{%block title%}Svensktillverkade möbler{%endblock%}
{%block content%}
<section id="hem" class="wrapper">
    <div class="home-products content">
        <div class="home-product" id="home-product-1">
            <div class="home-product-image">
            <img src="{{url_for('static', filename='img/products/ck.jpg')}}" alt="ck" width="auto" height="700px">
            </div>
            <div class="home-product-info">
                <h1>Level Circle Ek</h1>
                <p>
                    Runt soffbord i vitlack och träfanér med förvaringsutrymme mellan
                    skrivorna.
                </p>
                <h3>Material</h3>
                <p>
                    MDF medvitlackerad toppskiva och träfanér på undre skivan. Kromade
                    stålben.
                </p>
                <h3>Utförande</h3>
                <p>Helvit eller vit med ek, valnöt, svart poppel eller svart rot.</p>
            </div>
        </div>
    </div>
</section>
<section id="om-kant" class="wrapper">
    <div class="info content">
        <div class="info-text">
            <h1>Om kant</h1>
            <p>Kant Design drivs av Peter Björck och är ett företag med säte i Skanör/Falsterbo, som designar,
                tillverkar och marknadsför möbler för olika sammanhang - såväl hemmet som offentliga miljöer. Med fokus
                på funktionell design och hög kvalitet skapar Kant stilrena och unika möbler till konkurrenskraftiga
                priser. Produkter designade av Kant består av noga utvalda material och produktionen sker hos svenska
                möbeltillverkare - allt för att uppnå högsta kvalitet. </p>
        </div>
        <div class="info-img">
            <img src="{{url_for('static', filename='img/peter.jpg')}}" alt="Peter" width="auto" height="340px">
            <img src="{{url_for('static', filename='img/peter2.jpg')}}" alt="Peter2" width="auto" height="340px">
            <img src="{{url_for('static', filename='img/products/ck.jpg')}}" alt="bord" width="auto" height="340px">
        </div>
    </div>
</section>
<section id="kontakt" class="wrapper">
    <div class="kontakt content">
        <h1 class="info-title">Kontaktinfo</h1>
        <div class="kontakt-info">
            <div class="card">
                <div class="icon"><span class="fa fa-map-marker"></span></div>
                <div class="card-text">
                    <h3>Address</h3>
                    <p>Hedevägen 2 <br> 239 34 Skanör</p>
                </div>
            </div>
            <div class="card">
                <div class="icon"><span class="fa fa-phone"></span></div>
                <div class="card-text">
                    <h3>Telefon</h3>
                    <p>+46 (0)708 91 93 20</p>
                </div>
            </div>
            <div class="card">
                <div class="icon"><span class="fa fa-paper-plane"></span></div>
                <div class="card-text">
                    <h3>Email</h3>
                    <p>info@kant.se</p>
                </div>
            </div>
        </div>
        <h1 class="form-title">Hör av dig</h1>
        <div class="kontakt-form">
            <form action="info@kant.se" method="POST" enctype="multipart/form-data" name="EmailForm">
                <div class="name">
                    <label for="name">Namn</label>
                    <input type="text" name="name" id="name" placeholder="Namn">
                </div>
                <div class="email">
                    <label for="email">Email address</label>
                    <input type="email" name="email" id="email" placeholder="Email">
                </div>
                <div class="subject">
                    <label for="subject">Ämne</label>
                    <input type="text" name="subject" id="subject" placeholder="Ämne">
                </div>
                <div class="textarea">
                    <label for="message">Meddelande</label>
                    <textarea name="message" id="message" cols="30" rows="4" placeholder="Meddelande"></textarea>
                </div>
                <input type="submit" value="Submit" id="submit">
            </form>
        </div>
    </div>
</section>
{%endblock%}

app/templates/produkter/index.html
{%extends 'base.html'%}
{%block title%}Produkter{%endblock%}
{%block content%}
<div class="products">
  {% for product in products['products'] %}
  <div class="product">
    <h3>{{product['name']}}</h3>
    <img src="{{ url_for('static',filename=product['images'][0]) }}" alt="{{product['name']}}" />
    <p>
      {{product['description']}}
    </p>
  </div>
  {% endfor %}
</div>
{%endblock%}